# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en
  title: Open Phytoliths
  weight: 1
  params:
    description: Open Phytoliths Community - Building a shared vision for open science adoption and implementation among phytolith researchers globally.
fr:
  languageCode: fr
  contentDir: content/fr
  title: Open Phytoliths Community
  params:
    description: Open Phytoliths Community - Construire une vision partagée pour l'adoption et la mise en œuvre de la science ouverte parmi les chercheurs en phytolithes du monde entier.
es:
  languageCode: es
  weight: 3
  contentDir: content/es
  title: Open Phytoliths Community
  params:
    description: Comunidad abierta de fitolitos: creación de una visión compartida para la adopción e implementación de la ciencia abierta entre los investigadores de fitolitos de todo el mundo.

# Uncomment the lines below to configure your website in a second language.
#zh:
#  languageCode: zh-Hans
#  contentDir: content/zh
#  title: Chinese website title...
#  params:
#    description: Site description in Chinese...
#  menu:
#    main:
#      - name: 传
#        url: '#about'
#        weight: 1


